name: Auto Repo Snapshot

on:
  push:
    branches:
      - main
      - production
  workflow_dispatch:

jobs:
  auto-snapshot:
    runs-on: ubuntu-latest
    name: Auto Snapshot on Commit

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for full commit/tag context

      - name: Generate timestamp
        id: time
        run: echo "timestamp=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Prepare branch name
        id: branch
        run: |
          BRANCH_NAME="auto-snapshot-${{ github.run_number }}-${{ steps.time.outputs.timestamp }}"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create snapshot branch
        run: |
          git checkout -b "${{ steps.branch.outputs.branch_name }}"
          git push origin "${{ steps.branch.outputs.branch_name }}" || echo "⚠️ Branch push skipped (already exists)"

      - name: Create snapshot tag
        run: |
          TAG_NAME="auto-${{ github.run_number }}-${{ steps.time.outputs.timestamp }}"
          git tag -a "$TAG_NAME" -m "Auto snapshot created on push"
          git push origin "$TAG_NAME" || echo "⚠️ Tag push skipped (already exists)"

      - name: Log snapshot creation
        run: echo "✅ Auto snapshot branch + tag created successfully"
