name: Auto Repo Snapshot

on:
  workflow_dispatch:
    inputs:
      label:
        description: "Optional snapshot label (e.g. 'pre-deploy', 'backup')"
        required: false
        default: "manual"
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight UTC

jobs:
  snapshot:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate snapshot type
        id: type
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            echo "type=nightly" >> $GITHUB_OUTPUT
          else
            echo "type=manual" >> $GITHUB_OUTPUT
          fi

      - name: Compute label safely
        id: label
        shell: bash
        run: |
          INPUT_LABEL="${{ github.event.inputs.label || '' }}"
          LABEL="${INPUT_LABEL:-${{ steps.type.outputs.type }}}"
          SAFE_LABEL=$(echo "$LABEL" | sed 's/[^[:alnum:]_-]//g')
          echo "safe_label=$SAFE_LABEL" >> $GITHUB_OUTPUT

      - name: Create snapshot tag and log entry
        id: snapshot
        run: |
          SNAPSHOT_FILE="snapshot-log.md"
          DATE=$(date -u '+%Y-%m-%d %H:%M:%S UTC')
          SHORT_HASH=$(git rev-parse --short HEAD)
          TAG="snapshot-${DATE//[^a-zA-Z0-9]/-}-${{ steps.label.outputs.safe_label }}"
          
          echo "## 📦 Snapshot - $DATE" >> "$SNAPSHOT_FILE"
          echo "- Commit: $SHORT_HASH" >> "$SNAPSHOT_FILE"
          echo "- Label: ${{ steps.label.outputs.safe_label }}" >> "$SNAPSHOT_FILE"
          echo "- Type: ${{ steps.type.outputs.type }}" >> "$SNAPSHOT_FILE"
          echo "" >> "$SNAPSHOT_FILE"

          echo "Snapshot created: $TAG"
          echo "snapshot_tag=$TAG" >> $GITHUB_OUTPUT

      - name: Commit snapshot log
        run: |
          git config user.name "FalconerOne"
          git config user.email "actions@github.com"
          git add snapshot-log.md
          git commit -m "Auto Repo Snapshot: ${{ steps.label.outputs.safe_label }}" || echo "No changes to commit"
          git push

      - name: Confirm snapshot completion
        run: |
          echo "✅ Snapshot created successfully for label: ${{ steps.label.outputs.safe_label }}"
