name: Repo Snapshots (Auto + Manual + Nightly + Log)

on:
  workflow_dispatch: # manual trigger
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *" # every day at 1:00 AM UTC

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git identity
        run: |
          git config --global user.email "snapshot-bot@solarizedng.com"
          git config --global user.name "Solarized Snapshot Bot"

      - name: Create timestamp tag
        id: create_tag
        run: |
          TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
          TAG="auto-snapshot-${TIMESTAMP}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          git tag -a "$TAG" -m "Snapshot created: $TAG"
          git push origin "$TAG"

      - name: Update snapshot log
        run: |
          echo "### Snapshot Created: $TAG" >> snapshot-log.md
          echo "- Timestamp: $(date)" >> snapshot-log.md
          echo "- Triggered by: $GITHUB_ACTOR" >> snapshot-log.md
          echo "" >> snapshot-log.md

      - name: Commit and push snapshot log
        run: |
          git add snapshot-log.md
          git commit -m "Update snapshot log: $TAG" || echo "No changes to commit"
          git push origin main
