name: Manual Repo Snapshot

on:
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create snapshot branch
        run: |
          SNAPSHOT_BRANCH="snapshot-$(date +'%Y%m%d-%H%M%S')"
          git checkout -b "$SNAPSHOT_BRANCH"
          git push origin "$SNAPSHOT_BRANCH"

      - name: Confirm snapshot
        run: echo "✅ Snapshot created successfully on branch $SNAPSHOT_BRANCH"
